apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: busybox
        name: busybox
        command: 
          - sleep
          - "1000"
        envFrom:
          - configMapRef:
              name: cm-dep
              optional: false
